// GENERATED by scripts/generate-block-map.mjs — do not edit by hand.
// Run `pnpm gen` after adding or removing a block in registry/.

import dynamic from 'next/dynamic'
import type { ComponentType } from 'react'

/** Keyed by the flat registry name: <category>-<subcategory>-<slug>. */
export const BLOCK_MAP: Record<string, ComponentType> = {
  "marketing-feature-sections-alternating-with-screenshots": dynamic(() => import('@/registry/marketing/feature-sections/alternating-with-screenshots').then((m) => ({ default: m.default }))),
  "marketing-feature-sections-three-column-icons": dynamic(() => import('@/registry/marketing/feature-sections/three-column-icons').then((m) => ({ default: m.default }))),
  "marketing-feature-sections-with-feature-tabs": dynamic(() => import('@/registry/marketing/feature-sections/with-feature-tabs').then((m) => ({ default: m.default }))),
  "marketing-hero-sections-centered-editorial": dynamic(() => import('@/registry/marketing/hero-sections/centered-editorial').then((m) => ({ default: m.default }))),
  "marketing-hero-sections-centered-with-floating-cards": dynamic(() => import('@/registry/marketing/hero-sections/centered-with-floating-cards').then((m) => ({ default: m.default }))),
  "marketing-hero-sections-dark-with-dashboard": dynamic(() => import('@/registry/marketing/hero-sections/dark-with-dashboard').then((m) => ({ default: m.default }))),
  "marketing-hero-sections-dark-with-email-capture": dynamic(() => import('@/registry/marketing/hero-sections/dark-with-email-capture').then((m) => ({ default: m.default }))),
  "marketing-hero-sections-minimal-with-product-card": dynamic(() => import('@/registry/marketing/hero-sections/minimal-with-product-card').then((m) => ({ default: m.default }))),
  "marketing-hero-sections-simple-centered": dynamic(() => import('@/registry/marketing/hero-sections/simple-centered').then((m) => ({ default: m.default }))),
  "marketing-hero-sections-split-with-code": dynamic(() => import('@/registry/marketing/hero-sections/split-with-code').then((m) => ({ default: m.default }))),
  "marketing-hero-sections-split-with-stats": dynamic(() => import('@/registry/marketing/hero-sections/split-with-stats').then((m) => ({ default: m.default }))),
  "marketing-hero-sections-split-with-tabs": dynamic(() => import('@/registry/marketing/hero-sections/split-with-tabs').then((m) => ({ default: m.default }))),
  "marketing-hero-sections-with-ai-chat": dynamic(() => import('@/registry/marketing/hero-sections/with-ai-chat').then((m) => ({ default: m.default }))),
  "marketing-hero-sections-with-app-screenshot": dynamic(() => import('@/registry/marketing/hero-sections/with-app-screenshot').then((m) => ({ default: m.default }))),
  "marketing-hero-sections-with-mega-menu": dynamic(() => import('@/registry/marketing/hero-sections/with-mega-menu').then((m) => ({ default: m.default }))),
}

/** 15 blocks at generation time. */
export const BLOCK_COUNT: number = 15
